imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assets_version.php }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ['EcommerceCatalogAdminBundle']
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            apply_to: "\.less$"
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

doctrine_phpcr:
    session:
        backend:
            type: doctrinedbal
            connection: default
            caches:
                meta: liip_doctrine_cache.ns.meta
                nodes: liip_doctrine_cache.ns.nodes
        workspace: default
        username: admin
        password: admin
    odm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        locales: %fallback_locales%


liip_doctrine_cache:
    namespaces:
        meta:
            type: file_system
        nodes:
            type: file_system

fos_elastica:
    clients:
        default: { host: localhost, port: 9204 }


ecommerce_catalog:
    persistence:
        phpcr:
            enabled:          true
            manager_name:     null
            product_basepath: '/ecommerce/product'
            product_class:    'Ecommerce\Bundle\CatalogBundle\Doctrine\Phpcr\Product'
        orm:
            enabled:                 true
            manager_name:            null
            product_reference_class: 'Ecommerce\Bundle\CatalogBundle\Doctrine\Orm\ProductReference'
    property_files:
        - "%kernel.root_dir%/config/ecommerce/properties.yml"
        - "%kernel.root_dir%/config/ecommerce/properties2.yml"
    type_files:
        - "%kernel.root_dir%/config/ecommerce/types.yml"

ecommerce_elasticsearch:
    index: "sandbox"
    type: "products"


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
